### ISSUE TITLE
Process doesn't automatically close on exit

### ISSUE THREAD

**Issue by jzombie** [google/karma-webkit-launcher#1]
Thanks for making this launcher.

It works great except for one issue.

On my Mac, the process seems to stay open even after Karma has finished running, and I have to kill it using "killall Playwright."

If I get around to trying to fix it myself, I'll open a PR.

**Comment by MarkusBordihn** [comment]
Thanks for the report. The issue was Playwright related, which now using a shell script to launching the headless browser.
Because this shell script spawned additional processes, karma was unable to automatically kill them after the test was done and just killed the script itself.

I implemented a fix for "darwin" platforms, which makes sure to kill all child process for the specific karma test automatically after the test is done.

Please let me know if you see any additional issues.

**Comment by jzombie** [comment]
@MarkusBordihn It seems fixed now.  Thanks for the update.

**Comment by mgol** [comment]
I confirm the processes are correctly being closed now but the new version broke headless mode; bug report at #3.
